package me.angeschossen.lands.api.utils;

public enum TrustResult {
    FAILURE_SELF, FAILURE_ACCESS, FAILURE_ALREADY, FAILURE_MAX_MEMBERS, FAILURE_BANNED,FAILURE_WAR, FAILURE_OWN_LAND, FAILURE_PLAYER_MAX_LANDS, FAILURE_ALREADY_INVITED, FAILURE, SUCCESS_TRUSTED, FAILURE_OFFLINE, SUCCESS_INVITED, FAILURE_PLAYER_FLAG_RECEIVE_INVITES
}
